name: Publish

on:
  workflow_dispatch: {}
  push:
    branches: [master]

jobs:
  publish-gh:
    name: Publish Github Pages
    runs-on: ubuntu-latest
    env:
      JWT_ISSUER: ${{secrets.JWT_ISSUER}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint
      # - run: |
      #     git clone --single-branch --branch custom https://github.com/myin142/plyr.git
      #     cd plyr && npm i && npm run build && npm link ../ && cd ../
      - run: npm run build
      - run: npm run publish -- --api-key=$JWT_ISSUER --api-secret=$JWT_SECRET
      - run: cd dist/ && zip -r release.zip *
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest Release"
          files: |
            *.zip
